apiVersion: v2
name: transfergw
description: Kubernetes operator for migrating Ingress to Gateway APIs
type: application
version: 1.0.0
appVersion: "1beta1"
keywords:
  - kubernetes
  - ingress
  - gateway-api
  - migration
home: https://github.com/thev1ndu/transfergw
sources:
  - https://github.com/thev1ndu/transfergw
maintainers:
  - name: Thevindu Wickramaarachchi
    email: thevindu.w@yahoo.com
