# Development environment values
namespace: transfergw
createNamespace: true

image:
  repository: transfergw-controller
  tag: dev
  pullPolicy: Always

replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

logLevel: debug
enableWebhooks: true

leaderElection:
  enabled: false

podDisruptionBudget:
  enabled: false

rbac:
  create: true

serviceAccount:
  create: true
  name: transfergw-controller

crd:
  install: true
